### ISSUE TITLE
Video UI not showing in Open Stf Dashboard

### ISSUE THREAD

**Issue by gkrananth** [DeviceFarmer/stf_ios_support#55]
i removed in docker compose https and 443 port its giving problem.  Am able to do all things except the ui not showing.  When i use development tools in chrome am getting this error.

1.3af74560f0b1e33d1d60.chunk.js:80817 WebSocket connection to 'wss://192.168.0.109/frames/192.168.0.109/8000/x' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by gkrananth** [comment]
This trick worked for me

https://github.com/tmobile/stf_ios_support/issues/39#issuecomment-629121956

not sure is this right solution.  Its not smooth like localhost:8100/remote.  How can i send home button and install ipa file?  Can you please  help on this?

**Comment by gkrananth** [comment]
i installed the stf in outside then its working fine for me.

**Comment by nanoscopic** [comment]
The way the provided server configuration is ( this: https://github.com/tmobile/stf_ios_support/tree/master/server ), you are meant to use https.

For the most part, if you use http you are outside of support. I don't really see any point in supporting plain http.

If you absolutely have some reason you need to / insist upon using plain http, you can alter this line of code: https://github.com/tmobile/stf_ios_support/blob/master/coordinator/proc_device_unit.go#L43

Whatever that line is changed to needs to be present in the nginx config. Something equivalent to this:
https://github.com/tmobile/stf_ios_support/blob/master/server/nginx/nginx.conf#L78

The 8100 "remote" is hardly smooth. I'm not sure why it continues to be described in that way.

ws:// is insecure websocket. wss:// is secure.

The way it is designed to work:
1. browser reaches out to nginx on stf "server"
2. nginx routes that address back to the provider ( the mac mini running coordinator )
3. bin/ivf_pull ( using default settings ) on macos machine receives that websocket connection, and sends frames back through it

You can, if the network your client machine is on is the same as the network the macos provider machine is on, skip using nginx in the middle and get the frames directly from the provider machine.

That is what happens if you enable use of the frameServer settings here: https://github.com/tmobile/stf_ios_support/blob/master/coordinator/proc_device_unit.go#L27

**Comment by nanoscopic** [comment]
Closing ticket. I will close all tickets related to using Nginx without https from here on out. It's not supported and just confuses everyone.
