### ISSUE TITLE
No video in browser; WebSocket connection failed; response code: 502

### ISSUE THREAD

**Issue by dennispost** [DeviceFarmer/stf_ios_support#57]
Hey, we've tried to get STF to work. After trying different configuration that does't work at all, we have achieved to be able to control the device via browser but do not get any video / image.

We're getting this error in webbrowser:

> WebSocket connection to 'wss:://<server_ip>/frames/<server_ip>/8000/x' failed: Unexpected response code: 502

Quicktime: works
<server_ip>:8000: works and return image from device
Taking screenshots in browser: works
Control device in browser: works

Our configuration:
```json
{
  "xcode_dev_team_id": "xxxxxxx",
  "stf": {
    "ip": "<server_ip>",
    "hostname": "<server_ip>"
  },
  "network": {
    "interface": "en7"
  },
  "video": {
    "enabled": true,
    "use_vnc": false,
    "method": "avfoundation",
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 10
  },
  "install": {
    "root_path": "./",
    "config_path": "./config.json"
  }
}
```

Do you have any ideas how to fix this?

**Comment by nanoscopic** [comment]
How are you running STF server side? There needs to be a route within nginx run on STF server side to route the video ( /frames ) back to the device provider MacOS machine.

Eg: this is needed: https://github.com/tmobile/stf_ios_support/blob/master/server/nginx/nginx.conf#L78

**Comment by akaservus** [comment]
Hi @nanoscopic! Thank you for your answer.
We (@dennispost and me) had the default settings in nginx.conf for the location:

`^/frames/(?<client_ip>[^/]+)/(?<client_port>800[0-9])/x$`

I also tried with the updated settings:

`^/frames/(?<client_ip>192.168.1.[0-9]+)/(?<client_port>800[0-9])/x$`

Unfortunately without success. The same error.

**Comment by nanoscopic** [comment]
The connection shown is incorrect. The URL you have shown that it is attempting to use is `wss://192.168.1.136/frames/192.168.1.136/8000/x`. That means "connect through 192.168.1.136 to 192.168.1.136". The URL the device unit uses is generated here in the code: https://github.com/DeviceFarmer/stf_ios_support/blob/master/coordinator/proc_device_unit.go#L44

I can only assume that has been altered to be different/incorrect.
The `curIP` on a provider ( where coordinator is run ) / the MacOS machine with the IOS device connected, is the IP address of that Mac. In your example I believe it should be 192.168.1.129. You label that as "iPhone", but I think what you mean is "Mac with iPhone connected via USB".

Also, the URI prefix `wss://` means "connect via SSL". Without a port specified, it will use port 443. If you are getting a 50x from Nginx, I assume it is because you do not have Nginx configured to listen on SSL/port 443. I've said a number of times in a number of tickets that non-SSL Nginx is not supported. You can make it work but "not supported" means I don't want users cluttering the support tickets with requests on how to properly setup Nginx.

Please update your Nginx config / setup to use SSL.

**Comment by nanoscopic** [comment]
Closing ticket. Plain http is not supported. Use https / SSL with Nginx.
