### ISSUE TITLE
xcode 12 bug

### ISSUE THREAD

**Issue by r66ad** [DeviceFarmer/stf_ios_support#88]
There seems to be a bug with WebDriverAgent on xcode >12

Solution:
in case you get an error on make, do following: 
clone the stf_ios_support
edit config.json
make clone
copy boostrap.sh to repos/WebDriverAgent/Scripts
./init.sh
make

[bootstrap.sh.zip](https://github.com/DeviceFarmer/stf_ios_support/files/5561271/bootstrap.sh.zip)

Hope this helps

**Comment by nanoscopic** [comment]
Ding ding! Correct.

My fork of WebDriverAgent doesn't function on Xcode 12+ due to bugs in the way the Carthage dependency works.

The latest appium/WebDriverAgent upstream works fine though.

If you simply replace repos/WebDriverAgent with a clone of Appium upstream WDA repo then everything works.

I've been meaning to update the config to use upstream but I need to investigate and see if any additional changes are needed on top of upstream to support all the features.

**Comment by nanoscopic** [comment]
The latest updates just use upstream WDA instead.
